server:
  port: 9990
  servlet:
    context-path: /calorage
logging:
  level:
    com.ildardev.calorage: info
spring:
  data:
    mongodb:
      host: localhost
      database: calorage
  security:
    user:
      name: ildar
      password: ildar
